### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by pactode** [spatie/laravel-failed-job-monitor#44]
First of all, I want to say that it's a great package.

However, I end up receiving a "Too many open files" error. From what I have been able to troubleshoot so far, it is related to the Guzzle implementation and it happens when handling the SlackMessage for this package.

I'd appreciate if you have any tips on how to resolve this in case you've experienced something similar.

Stacktrace for the error:
```
[2018-10-08 06:45:03] production.ERROR: include(/home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Exception/ConnectException.php): failed to open stream: Too many open files {"exception":"[object] (ErrorException(code: 0): include(/home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Exception/ConnectException.php): failed to open stream: Too many open files at /home/forge/default/releases/20181003152717/vendor/composer/ClassLoader.php:444)
[stacktrace]
#0 /home/forge/default/releases/20181003152717/vendor/composer/ClassLoader.php(444): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(/home/f...', '/home/forge/kar...', 444, Array)
#1 /home/forge/default/releases/20181003152717/vendor/composer/ClassLoader.php(444): include()
#2 /home/forge/default/releases/20181003152717/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/home/forge/kar...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('GuzzleHttp\\\\Exce...')
#4 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(185): spl_autoload_call('GuzzleHttp\\\\Exce...')
#5 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)
#6 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#7 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#8 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#13 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#14 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#15 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#16 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#17 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Client->requestAsync('post', Object(GuzzleHttp\\Psr7\\Uri), Array)
#18 /home/forge/default/releases/20181003152717/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('post', 'https://hooks.s...', Array)
#19 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Notifications/Channels/SlackWebhookChannel.php(45): GuzzleHttp\\Client->__call('post', Array)
#20 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(127): Illuminate\\Notifications\\Channels\\SlackWebhookChannel->send(Object(Spatie\\FailedJobMonitor\\Notifiable), Object(App\\Notifications\\FailedJobNotification))
#21 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(102): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(Spatie\\FailedJobMonitor\\Notifiable), '2f38c236-9843-4...', Object(App\\Notifications\\FailedJobNotification), 'slack')
#22 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#23 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(104): Illuminate\\Notifications\\NotificationSender->withLocale(NULL, Object(Closure))
#24 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(76): Illuminate\\Notifications\\NotificationSender->sendNow(Array, Object(App\\Notifications\\FailedJobNotification))
#25 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(42): Illuminate\\Notifications\\NotificationSender->send(Array, Object(App\\Notifications\\FailedJobNotification))
#26 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(Spatie\\FailedJobMonitor\\Notifiable), Object(App\\Notifications\\FailedJobNotification))
#27 /home/forge/default/releases/20181003152717/vendor/spatie/laravel-failed-job-monitor/src/FailedJobNotifier.php(23): Spatie\\FailedJobMonitor\\Notifiable->notify(Object(App\\Notifications\\FailedJobNotification))
#28 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Spatie\\FailedJobMonitor\\FailedJobNotifier->Spatie\\FailedJobMonitor\\{closure}(Object(Illuminate\\Queue\\Events\\JobFailed))
#29 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Queu...', Array)
#30 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/FailingJob.php(36): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Queu...')
#31 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(440): Illuminate\\Queue\\FailingJob::handle('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(SoapFault))
#32 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(426): Illuminate\\Queue\\Worker->failJob('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(SoapFault))
#33 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(358): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1, Object(SoapFault))
#34 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(331): Illuminate\\Queue\\Worker->handleJobException('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions), Object(SoapFault))
#35 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#36 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#37 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'orders', Object(Illuminate\\Queue\\WorkerOptions))
#38 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'orders')
#39 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#40 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#41 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#42 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#43 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#44 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#45 /home/forge/default/releases/20181003152717/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#46 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#47 /home/forge/default/releases/20181003152717/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /home/forge/default/releases/20181003152717/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /home/forge/default/releases/20181003152717/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 /home/forge/default/releases/20181003152717/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 /home/forge/default/releases/20181003152717/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 {main}
```

**Comment by freekmurze** [comment]
Didn't come across this error myself yet. I suspect this error is caused by something in your app and not by our package. 

If you do find a bug in our package that needs to be fixed, send a PR.
